### ISSUE TITLE
Adding Title and Description to fiddles

### ISSUE THREAD

**Issue by BrianChen** [esfiddle/esfiddle#102]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)

@joshghent suggested that we should add a Title and Description to each fiddle. 

I think one way we can do this is instead of showing a blank console when initially selecting a fiddle example, we can provide a brief description of what the example is for and explain the code as well.

This would only be displayed when you select first select an example but would disappear once you run the code and the only way for it to show again would be to reselect the example.

This is just an idea, if anyone has any other suggestion please let me know! @SaraVieira

![esfiddle - title and description on fiddles](https://cloud.githubusercontent.com/assets/16259288/24084232/a8e2f3ce-0cbc-11e7-97ac-3a39231dc81c.png)

**Comment by joshghent** [comment]
@BrianChen Apologies for not getting back to you on this one. Been a little under the weather! 😷 

That's a great idea! I don't think we can/should do it exactly as pictured but it's a great start.

There are 2 possible solutions I have to this
1.  Have a comment block above each example like this
```js
/////////////////////////////////////////////////////////////////////////
Example: Promises
Description: This example code is designed to return a promise
You can see in the example that we create 'A' as a constant.
We then pass that to .....
/////////////////////////////////////////////////////////////////////////
```

2. Add a new key to the window.examples called `onStart`. This would be a string of code to run when the example code is opened. Since it is not included in the actual example code it would not show but it would still run. 

Let me know what you guys think.

**Comment by BrianChen** [comment]
@joshghent I explored the two options you mentioned.

For the first example, this is definitely an option and is easy to implement but there are a few things to watch out for.
1. Setting a max-width on the codemirror so that long descriptions would not prevent users from seeing the console. 
2. Comment block may look messier than other options. Also need to manually check that the code runs everytime we add title/description comment block.

For the second example, I am actually not sure what you wanted to do with the onStart.  Do you mean that the onStart code will console log the title and description which would display on the console section? If so I think this would be the better option.

**Comment by BrianChen** [comment]
Had some time to work on this. I decided to implement the title and description by adding an onStart to each example and running the code when an example is selected.

This is what it would look like when the example is first selected.
<img width="1280" alt="esfiddle - title and description" src="https://cloud.githubusercontent.com/assets/16259288/24641734/15ec3ed4-18d0-11e7-94cf-8f81954c79f0.png">

An onStart property would be added to each example like this.
```JavaScript
window.es6Example.arrow.onStart =
`
console.log('Arrow Functions');
console.log('This example code is designed to show how to use arrow functions in es6.  There are a few different syntax that can be used.');
`;
```

The onStart would run every time the example is selected/changed.
```JavaScript
    window.exampleSelector.onchange = () => {
      if (window.exampleSelector.value) {
        let code = 'Example Can Not Be Found';
        let onStart = 'console.log(Example Can Not Be Found)';

        if (window.es6Example[window.exampleSelector.value]) {
          ({ code, onStart } = window.es6Example[window.exampleSelector.value]);

        } else if (window.es7Example[window.exampleSelector.value]) {
          ({ code, onStart } = window.es7Example[window.exampleSelector.value]);
        }

        fiddle.setValue(onStart);
        runFiddle();
        fiddle.setValue(code);

      }
    };
```

@joshghent @SaraVieira If you guys have any other suggestions, please let me know.  If this looks good I will go ahead and add title and description to each example.

**Comment by asiyani** [comment]
Hi @BrianChen Thank you very much for working on this. Its looks good for examples fiddle. 

We also looking for something similar for all fiddles. We need input from user regarding Title and description while saving fiddle. 
This will require some front end and back end changes, but if you want you can work on front end side of it and I will look in to backend.  

Front End work requires:

- Deciding where to make UI changes on Main page.

- Add Text input  for Title and Description. Where Description is optional. 

- Collect data and send it to server while saving fiddle as title and description property along with other fiddle properties. (POST /SAVE)

- updating same UI component while fetching fiddle from server. ( GET /fiddles )

Back End work requires:

- Updating  GET /fiddles  & POST /SAVE APIs.

- Updating myProfile template to show Titles instead of fiddle numer.

**Comment by lailavinson** [comment]
Hi, is help wanted with any of the items listed above? Interested in contributing.

**Comment by joshghent** [comment]
@lailavinson Hi there, apologies for the late reply!
Yeah we are still looking to get this done. We need some kind of UI elements or interaction whereby you can set the title and description for a Fiddle. Is this something you think you could do? We are very open to suggestions on how this should be done. 👍

**Comment by joshghent** [comment]
@lailavinson Hey there, I kind of let this issue drift but wanted to check in to see if you were doing ok with your PR and this issue? Can I or anyone else in the team help? Contact me on gitter if you need any assistance! 👍 

If you no longer have time to work on it, that's fine too. We appreciate people generously donate their precious free time to this!

**Comment by preyneyv** [comment]
Hey @joshghent, I have some free time, and I was wondering if I could tackle the front-end changes. I've never contributed to an open-source project before, but I am fairly experienced in front-end and back-end design.

**Comment by joshghent** [comment]
@preyneyv By all means! This would be great. We are looking at rewriting this as a SPA in either React or Vue with the aim of providing an Offline-first experience. With the redesign we are looking at doing this work at the same time. Is this something you'd like to handle? (not all of it of course!)

**Comment by preyneyv** [comment]
@joshghent I would love to work on a new design. Give me a few days and I'll send it over. Let me open that up as another issue though. The title is misleading.

**Comment by joshghent** [comment]
Doing this as part of the redesign and new API so going to close this off for now.
