### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#8]
So it's time we added tests for the API so we can be confident that all new features we add and bugs we fix still leave the site functional. 

The testing framework does not matter. I think we will use a mix of mocha, chai and perhaps selenium if needed.

I suggest tests for the following:
- [ ] Save a fiddle
- [ ] Load a fiddle
- [ ] Horizontal and Vertical buttons work
- [ ] Code lints correctly

Please feel free to suggest more and add them!

**Comment by asiyani** [comment]
I have return 2 test cases for API testing on node side. Its for GET /fiddles/fiddle and POST /save. This test will only test node side like if fiddle is saved in db and correct fiddle is passed to client. I am not sure if this is what you looking for. 

I am using mocha, chai and superTest for this. 

While writing this test I found some issues I am not sure if its a bug for by Design. 
  --> Get /fiddles/fiddle should return 404 when fiddle is not found  but its returning 200 and a message. 
 --> When we save same fiddle again it gets saved as another fiddle instead of updating original one.

I have commited my changes to this [fork](https://github.com/asiyani/esfiddle).

let me know if this is was you looking ?

**Comment by joshghent** [comment]
@asiyani That's great work, thank you! If you can think of any more test cases to add (even if they fail) then go for it, the more the better! Only 1 thing is to add the `npm run test-node` to the `npm test` command so it will get run by the CI, but looks good!

The first issue, I will make an issue to fix that, so change the test to expect a 404 error.

The second issue is because we do not have logins for the site, we do not want anyone viewing a fiddle to be able to change it! Resaving functionality will be added once github signins are done.

Submit a PR and I'll merge it in 👍

**Comment by asiyani** [comment]
@joshghent I am trying to submit pull request but it failing on tarvis test 

Error message:- [LINK](https://travis-ci.org/esfiddle/esfiddle/builds/194137740)
/home/travis/build/esfiddle/esfiddle/node_modules/mongodb/lib/url_parser.js:18
    throw new Error('invalid schema, expected mongodb');

for this code....

`mongo.connect(String(process.env.MONGODB_URI), function (err, db) {
    fiddles = db.collection('fiddles');
    fiddles.insert(testFiddle);
});`

but this code is same as in api.js file.  not sure why its failing api.test.js.. any idea ? 

Thanks.

**Comment by joshghent** [comment]
@asiyani I know the issue, submit the PR. It's ok if it's failing for now as we need to fix things like the 404 response etc. Submit the PR and I'll fix it up. I'll have a think of some more tests to add too.

**Comment by asiyani** [comment]
Hi 
I have submitted pull request.
travis test is still failing with 'Error: invalid schema, expected mongodb'. 
Please let me know what is causing this issue. 

If you think of any other test let me know. 

Thanks

**Comment by joshghent** [comment]
@asiyani it's caused by Travis not having the environment variables configured correctly. I'll fix it later, thanks for your PR. I'll take a look at this later

**Comment by joshghent** [comment]
Fixed in https://github.com/esfiddle/esfiddle/pull/36

Thanks to @asiyani for his work and first PR 🎉
